sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  github-token: $GH_TOKEN
  type: git
  repo: https://github.com/redcatH/redcatH.github.io.git
  branch: master